name: Build and Push to Repo Built

on:
  push:
    branches:
      - main  # or your default branch name for Repo A

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.1'

    - name: Install dependencies
      run: npm ci

    - name: Make build script executable
      run: chmod +x ./build_script.sh

    - name: Build project
      run: bash ./build_script.sh

    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Clone or initialize Repo Built
      run: |
        if git clone https://x-access-token:${{ secrets.REPO_BUILT_TOKEN }}@github.com/mankaistep/fast-ai-rewrite-app-built.git; then
          cd fast-ai-rewrite-app-built
        else
          mkdir fast-ai-rewrite-app-built
          cd fast-ai-rewrite-app-built
          git init
          git remote add origin https://x-access-token:${{ secrets.REPO_BUILT_TOKEN }}@github.com/mankaistep/fast-ai-rewrite-app-built.git
          echo "# Fast AI Rewrite App Built" > README.md
          git add README.md
          git commit -m "Initial commit"
          git branch -M main
          git push -u origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_BUILT_TOKEN }}

    - name: Copy built files to Repo Built
      run: |
        cd fast-ai-rewrite-app-built
        git checkout main || git checkout -b main
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.gitignore' -exec rm -rf {} +
        cp -R ../temp_built/* .

    - name: Verify built files
      run: |
        cd fast-ai-rewrite-app-built
        echo "Contents of built repository:"
        ls -R
        echo "Checking for .next folder:"
        if [ -d ".next" ]; then
          echo ".next folder exists"
          ls -la .next
        else
          echo ".next folder is missing"
          exit 1
        fi

    - name: Commit and push to Repo Built
      run: |
        cd fast-ai-rewrite-app-built
        git add .
        git commit -m "Update built files" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_BUILT_TOKEN }}
  