name: Build and Push to Repo Built

on:
  push:
    branches:
      - main  # or your default branch name for Repo A

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'

      - name: Install dependencies
        run: npm ci

      - name: Make build script executable
        run: chmod +x ./build_script.sh

      - name: Build project
        run: bash ./build_script.sh

      - name: Debug - List directories
        run: |
          echo "Current directory:"
          ls -la
          echo "temp_built directory:"
          ls -la temp_built
          echo "temp_built/.next directory:"
          ls -la temp_built/.next

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Clone or initialize Repo Built
        run: |
          git clone https://x-access-token:${{ secrets.REPO_BUILT_TOKEN }}@github.com/mankaistep/fast-ai-rewrite-app-built.git
          cd fast-ai-rewrite-app-built
          git lfs install
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_BUILT_TOKEN }}

      - name: Copy built files to Repo Built
        run: |
          cd fast-ai-rewrite-app-built
          git checkout main || git checkout -b main
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.gitignore' ! -name '.gitattributes' -exec rm -rf {} +
          cp -R ../temp_built/* .
          cp -R ../temp_built/.next .

      - name: Setup Git LFS tracking
        run: |
          cd fast-ai-rewrite-app-built
          git lfs track "node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node"
          git add .gitattributes
          git commit -m "Update .gitattributes for LFS" || echo "No changes to commit for .gitattributes"

      - name: Commit and push to Repo Built
        run: |
          cd fast-ai-rewrite-app-built
          git add .
          git commit -m "Update built files" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_BUILT_TOKEN }}